services:
  postgres:
    image: postgres:17-alpine
    container_name: iw-postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - iw-net

  pgadmin:
    image: elestio/pgadmin:REL-8_12
    container_name: iw-pgadmin
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ua.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - iw-net

  application:
    build: .
    container_name: iw-application
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - iw-net

networks:
  iw-net:
    driver: bridge
