services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 10s
      retries: 5
    # volumes:
      # - ./.data:/docker-entrypoint-initdb.d
    networks:
      - iw-net

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@ua.es
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_SERVER_JSON_FILE=/.data/servers.json
    volumes:
      - ./.data:/.data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - iw-net

  application:
    build: .
    container_name: application
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=prod
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - iw-net

networks:
  iw-net:
    driver: bridge
