services:
  postgres:
    image: postgres:17-alpine
    container_name: iw-db
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - iw-net

  application:
    build: .
    container_name: iw-app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - iw-net

networks:
  iw-net:
    driver: bridge
